server:
  port: 9988
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: uwjx.com:8848
    gateway:
      discovery:
        locator:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
